apiVersion: v1
kind: ConfigMap
metadata:
  name: ${IMAGE_NAME}-app-config
  namespace: $OPENSHIFT_PROJECT
data:
  DYNATRACE_MIN_LOG_LEVEL: "Information"
  DYNATRACE_INGEST_URL: "https://ubq67256.live.dynatrace.com/api/v2/logs/ingest"
